# Site settings
name: Rajesh Kolli
title: Rajesh Kolli | Android Application Developer
description: An innovative android developer focused on building beautiful applications and managing applications from analysis to release.
url: "https://rjkolli7.github.io/"
baseurl: ""
email: rjkolli7@gmail.com
cover: ""
logo: ""
resume: ""
social:
  - title: email
    url: mailto:rjkolli7@gmail.com
  - title: github
    url: https://github.com/rjkolli7
  - title: linkedin
    url: https://www.linkedin.com/in/rajesh-kolli-0b0ba056/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

  